name: CIfuzz
on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build Docker image
              run: ./build.sh
            - name: Run Docker container
              run: ./run.sh
